### ISSUE TITLE
mm1-hat donkey car driver

### ISSUE THREAD

**Issue by peterpanstechland** [robotics-masters/mm1-hat-cpy-native#3]
Seems like the donkey car use Pi i2c GPIO pins to communicate with the ADD-ON BOARD which is connected to the servo and ESC on RC car, the links below are the library for the two supported ADD-ON BOARD:
[Adafruit_MotorHAT_Motors](https://github.com/peterpanstechland/Adafruit-Motor-HAT-Python-Library/blob/master/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py)
[Adafruit_PCA9685](https://github.com/peterpanstechland/Adafruit_Python_PCA9685/blob/master/Adafruit_PCA9685/PCA9685.py)

We need to implement the mm1-hat python library for Donkey car.
Then ADD-ON BOARD library is called in donkeycar/parts/actuator.py (https://github.com/peterpanstechland/donkeycar/blob/dev/donkeycar/parts/actuator.py).

BTW the donkey car program won't start without an motor/servo driver ADD-ON BOARD.

**Comment by wallarug** [comment]
This should be done using SeeSaw and I2C.

**Comment by peterpanstechland** [comment]
1. Need to find out how to enable the SERVO and RC_CH pins associate with the SERCOMs.
2. Then figure out the sending PWM signal to the pins.

**Comment by wallarug** [comment]
@peterpanstechland 

https://github.com/robotics-masters/mm1-hat-seesaw/blob/master/circuitpython/robohatmm1.py

I am working on it over here.  Nothing has been modified to work in that version of the code.  The correct pin mapping needs to be done.

**Comment by peterpanstechland** [comment]
okey, i think we should move this to the mm1-hat-seesaw repo...so probably close this one and link to the seesaw repo...
